# Generated by Django 3.1.4 on 2021-02-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='tel',
            field=models.CharField(max_length=10, verbose_name='連絡電話'),
        ),
    ]
