# Generated by Django 3.1.4 on 2021-02-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equip', '0001_initial'),
        ('borrower', '0002_auto_20210205_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.DateTimeField(auto_now_add=True, verbose_name='借用時間')),
                ('returned', models.DateTimeField(null=True, verbose_name='歸還時間')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.borrower')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.equip')),
            ],
        ),
    ]
