# Generated by Django 3.1.4 on 2021-02-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=255, verbose_name='設備編號')),
                ('pattern', models.CharField(max_length=255, verbose_name='型號')),
                ('PropertyNumber', models.CharField(max_length=255, verbose_name='財產編號')),
                ('comment', models.CharField(max_length=255, verbose_name='備註')),
            ],
        ),
    ]
